### ISSUE TITLE
How to handle non open source projects

### ISSUE THREAD

**Issue by robsdedude** [Rinnegatamante/VitaDB#11]
To prevent further off-topic discussion in #3 let's open a new issue for this.

 - I'm not defending anything I was just asking about things I didn't know. To me it seemed (at first glance) that ONElua was floss.
 - I'm just thinking how things could be improved. Here is an idea: why not let the users decide if they want non-floss software or not by listing them but adding a flag/warning?

**Comment by Rinnegatamante** [comment]
There's a difference between closed source projects and closed source projects using GPL code. The first doesn't break any license (eg: http://vitadb.rinnegatamante.it/#/info/414 ), the second does.
As a developer, i'm not going to give advertisement to someone not respecting a license born for developers.
I won't tolerate more discussions about this tempering the Issue tracker with off topic discussions.
If you want a place where you can download whatever kind of software (malwares, software made by discutible people and software made by people not giving a shit about licenses) you can go on Brewology.
