### ISSUE TITLE
Problems downloading with Vita Homebrew Browser

### ISSUE THREAD

**Issue by rsn8887** [Rinnegatamante/VitaDB#7]
Vita HBB now fails do download anything from bintray with the error message “network: cannot send request”, on 3.60. The Retroarch download is on a separate server and works fine, but only if I set the url to http. Https doesn’t work either there.

Something changed on bintray maybe? Maybe the https certificate or some such. I tried to change a link (Pfba) from https to http but still didn’t work. Maybe bintray forces everything to a news https protocol not supported by 3.60 kernel?

**Comment by Rinnegatamante** [comment]
That's not a problem of VitaDB but just an issue with VHBB. Proper place to report this is probably: https://github.com/devnoname120/vhbb
