### ISSUE TITLE
Could you add Plugins Manager v.2.01?

### ISSUE THREAD

**Issue by azumukupoe** [Rinnegatamante/VitaDB#8]
Thank you in advance.

**Comment by Rinnegatamante** [comment]
Last available version is the 2.0 from 10 september. Btw please contact me on Twitter or Discord for these kind of stuffs. Issue tracker here should be related to technical issues only if possible.

**Comment by azumukupoe** [comment]
I have 2.01 installed on my vita
Downloaded the vpk from bitbucket
It should be there
